#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# p0-s5-dashboard-wire.sh — Phase 0, Step 5: Wire alex-dashboard to MCP bridge
#
# Ensures NEXT_PUBLIC_MCP_URL is set in the alex-dashboard .env.local so the
# MCP client in openrouter-crew-platform points at the local bridge.
# Assigned crew: Lt. Uhura (cross-system integration, communication pathways).
# MCP tool on failure: run_crew_agent
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/lib/crew-fail.sh"

STEP="p0-s5-dashboard-wire"
step_header "PHASE 0 — CONVERGENCE" "Step 5: Wire Dashboard → MCP Bridge"

set -a; source "$ROOT/.env" 2>/dev/null || true; set +a

BRIDGE_PORT="${MCP_BRIDGE_PORT:-3002}"
MCP_URL="http://localhost:${BRIDGE_PORT}"

# ── Locate openrouter-crew-platform ──────────────────────────────────────────
# Try siblings of the current repo first, then common locations
ORC_CANDIDATES=(
  "$(dirname "$ROOT")/openrouter-crew-platform"
  "$HOME/Dev/openrouter-crew-platform"
  "$HOME/openrouter-crew-platform"
)

ORC_ROOT=""
for candidate in "${ORC_CANDIDATES[@]}"; do
  if [[ -d "$candidate" ]]; then
    ORC_ROOT="$candidate"
    break
  fi
done

if [[ -z "$ORC_ROOT" ]]; then
  crew_fail \
    --step    "$STEP" \
    --persona "lt_uhura" \
    --tool    "run_crew_agent" \
    --tool-args '{"objective": "Clone openrouter-crew-platform and configure NEXT_PUBLIC_MCP_URL=http://localhost:3002 in apps/alex-dashboard/.env.local", "agents": [{"persona": "Lt. Uhura", "role": "Cross-System Integration Analyst", "goal": "Set up communication channel between ai-enterprise-os MCP bridge and alex-dashboard"}]}' \
    --context "openrouter-crew-platform not found in any expected location. It must be cloned before this step can wire the dashboard." \
    --error   "Searched: ${ORC_CANDIDATES[*]} — run: git clone https://github.com/familiarcat/openrouter-crew-platform $(dirname "$ROOT")/openrouter-crew-platform"
  exit 1
fi

echo "  ✔  openrouter-crew-platform found: $ORC_ROOT"

# ── Locate alex-dashboard ─────────────────────────────────────────────────────
DASHBOARD_DIR="$ORC_ROOT/apps/alex-dashboard"
if [[ ! -d "$DASHBOARD_DIR" ]]; then
  crew_fail \
    --step    "$STEP" \
    --persona "lt_uhura" \
    --tool    "run_crew_agent" \
    --tool-args '{"objective": "Locate or scaffold the alex-dashboard Next.js app within openrouter-crew-platform/apps/", "agents": [{"persona": "Lt. Uhura"}]}' \
    --context "apps/alex-dashboard not found inside $ORC_ROOT." \
    --error   "Directory not found: $DASHBOARD_DIR"
  exit 1
fi

echo "  ✔  alex-dashboard found: $DASHBOARD_DIR"

# ── Set NEXT_PUBLIC_MCP_URL in .env.local ─────────────────────────────────────
ENV_LOCAL="$DASHBOARD_DIR/.env.local"
echo ""
echo "  Configuring $ENV_LOCAL ..."

# Write or update NEXT_PUBLIC_MCP_URL
if [[ -f "$ENV_LOCAL" ]]; then
  if grep -q "NEXT_PUBLIC_MCP_URL" "$ENV_LOCAL"; then
    # Update existing value
    CURRENT=$(grep "NEXT_PUBLIC_MCP_URL" "$ENV_LOCAL" | head -1)
    echo "  Current: $CURRENT"
    # Use sed to replace the line
    sed -i.bak "s|^NEXT_PUBLIC_MCP_URL=.*|NEXT_PUBLIC_MCP_URL=${MCP_URL}|" "$ENV_LOCAL"
    rm -f "${ENV_LOCAL}.bak"
    echo "  ✔  Updated NEXT_PUBLIC_MCP_URL → $MCP_URL"
  else
    echo "" >> "$ENV_LOCAL"
    echo "NEXT_PUBLIC_MCP_URL=${MCP_URL}" >> "$ENV_LOCAL"
    echo "  ✔  Appended NEXT_PUBLIC_MCP_URL=$MCP_URL to $ENV_LOCAL"
  fi
else
  # Create .env.local with required vars, copying from parent .env
  {
    echo "# Auto-generated by p0-s5-dashboard-wire.sh"
    echo "NEXT_PUBLIC_MCP_URL=${MCP_URL}"
    # Propagate shared keys if set
    [[ -n "${OPENROUTER_API_KEY:-}" ]] && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
    [[ -n "${SUPABASE_URL:-}" ]]       && echo "NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}"
    [[ -n "${SUPABASE_KEY:-}" ]]       && echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_KEY}"
    [[ -n "${REDIS_URL:-}" ]]          && echo "REDIS_URL=${REDIS_URL}"
  } > "$ENV_LOCAL"
  echo "  ✔  Created $ENV_LOCAL"
fi

# ── Also write to the root ai-enterprise-os .env if NEXT_PUBLIC_MCP_URL missing
echo ""
if ! grep -q "NEXT_PUBLIC_MCP_URL" "$ROOT/.env" 2>/dev/null; then
  echo "NEXT_PUBLIC_MCP_URL=${MCP_URL}" >> "$ROOT/.env"
  echo "  ✔  Added NEXT_PUBLIC_MCP_URL to $ROOT/.env"
fi

# ── Verify the MCP API route file exists in alex-dashboard ───────────────────
echo ""
echo "  Checking alex-dashboard MCP API route..."
MCP_ROUTE=$(find "$DASHBOARD_DIR/app/api/mcp" "$DASHBOARD_DIR/pages/api/mcp" \
  -name "*.ts" -o -name "*.js" 2>/dev/null | head -3 || true)

if [[ -z "$MCP_ROUTE" ]]; then
  echo "  ⚠  No MCP API route found in alex-dashboard/app/api/mcp/ or pages/api/mcp/"
  echo "     The dashboard may not yet have an MCP client route — this is expected before Phase 1."
else
  echo "  ✔  MCP route(s) found:"
  echo "$MCP_ROUTE" | sed 's/^/    /'
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "  Dashboard wiring summary:"
echo "    ORC platform : $ORC_ROOT"
echo "    alex-dashboard: $DASHBOARD_DIR"
echo "    .env.local   : $ENV_LOCAL"
echo "    MCP URL      : $MCP_URL"

phase_pass "$STEP"
